name: Quick Test

on:
  push:
    branches: [ main, develop, auto_test, 'feature/*', 'test/*' ]
  pull_request:
    branches: [ main, develop, auto_test, 'feature/*', 'test/*' ]


jobs:
  quick-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y gfortran libopenblas-dev liblapack-dev

    - name: Configure and build
      run: |
        ./configure --prefix=$PWD/install
        make -j$(nproc)
        make install

    - name: Run quick tests
      run: |
        cd test
        make
        # Run only essential tests for quick feedback
        echo "Running quick test suite..."
        ./solve_cc.x < complex_freq.in > solve_cc.log 2>&1
        ./solve_rr.x < real_freq.in > solve_rr.log 2>&1
        
        # Check if tests completed successfully
        if grep -q "Converged\|converged\|SUCCESS" solve_cc.log; then
          echo "✓ solve_cc.x test passed"
        else
          echo "✗ solve_cc.x test may have failed"
          cat solve_cc.log
        fi
        
        if grep -q "Converged\|converged\|SUCCESS" solve_rr.log; then
          echo "✓ solve_rr.x test passed"
        else
          echo "✗ solve_rr.x test may have failed"
          cat solve_rr.log
        fi

    - name: Test sample application
      run: |
        # Find ShiftK.out executable (check for libtool wrapper or actual executable)
        if [ -f "app/src/ShiftK.out" ] && [ -x "app/src/ShiftK.out" ]; then
          if head -1 app/src/ShiftK.out | grep -q "#!/bin/sh"; then
            # It's a libtool wrapper script, use the actual executable
            if [ -f "app/src/.libs/ShiftK.out" ] && [ -x "app/src/.libs/ShiftK.out" ]; then
              SHIFTK_PATH="app/src/.libs/ShiftK.out"
            else
              echo "ERROR: Actual executable not found in .libs directory"
              exit 1
            fi
          else
            SHIFTK_PATH="app/src/ShiftK.out"
          fi
        else
          echo "ERROR: ShiftK.out not found in app/src/"
          exit 1
        fi
        
        echo "Using ShiftK: $SHIFTK_PATH"
        cd app/sample/denovo
        # Use absolute path to avoid path issues
        ABSOLUTE_SHIFTK_PATH=$(realpath "$PWD/../../$SHIFTK_PATH" 2>/dev/null || echo "$PWD/../../$SHIFTK_PATH")
        echo "Absolute path: $ABSOLUTE_SHIFTK_PATH"
        echo "File exists: $([ -f "$ABSOLUTE_SHIFTK_PATH" ] && echo "YES" || echo "NO")"
        echo "File executable: $([ -x "$ABSOLUTE_SHIFTK_PATH" ] && echo "YES" || echo "NO")"
        
        if [ -f "$ABSOLUTE_SHIFTK_PATH" ] && [ -x "$ABSOLUTE_SHIFTK_PATH" ]; then
          timeout 30s "$ABSOLUTE_SHIFTK_PATH" namelist.def || echo "Sample test completed"
          test -f dynamicalG.dat && echo "✓ Sample application test passed"
        else
          echo "ERROR: ShiftK executable not accessible at: $ABSOLUTE_SHIFTK_PATH"
          echo "File exists: $([ -f "$ABSOLUTE_SHIFTK_PATH" ] && echo "YES" || echo "NO")"
          echo "File executable: $([ -x "$ABSOLUTE_SHIFTK_PATH" ] && echo "YES" || echo "NO")"
        fi
